utworzenie szkieletu menu
dawidmarek95x/team-project-1 pull request #9
Opened 2022-03-16 12:46 UTC by Marektg

2022-03-16 21:21 UTC, dawidmarek95x reviewed
1. Linijka 2: 
a) Zmień dla `<div class="header-section__menu">` nazwę klasy na `menu`

2. Linijki 3-7:
a) Moim zdaniem za dużo zagnieżdżeń, więc usunął bym `<div class="menu-logo">` lub jeśli chcesz zostawić, bo uważasz, że przyda się do stylizacji to zmień nazwę klasy na `menu__logo--container`.
b) W `<a href="#" class="menu-logo__link">` zmienił bym klasę na menu__logo-link
c) W `<img src="images/logo.jpg" alt="icecream" class="menu-logo__link__logo">` zmienił bym klasę na `menu__logo`. Tak jak używasz jest niezgodnie z konwencją BEM - zbyt rozbudowane, bo masz `blok__element1__element2`, a powinien być max 1 element po nazwie bloku.
d) W tym samym `<img>` dodaj na początku ścieżki `./` przed `images/logo.jpg`

3. Linijki 8 - 18:
a) Zmień w `<nav class="menu-nav">` nazwe klasy na `navigation` - nawigacja może być później oddzielnym komponentem SCSS
b) Zmień w `<ul class="menu-nav__list">` nazwę klasy na `nav`
c) Zmień dla elementów `<li class="menu-nav__list__item">` nazwy klas na `nav__item`
d) Zmień dla linków `<a class="menu-nav__list__item-link">` nazwy klas na `nav__link`. Dla linku aktywnego dodaj dodatkowo klasę `link--active`.

4. Linijki 19 - 23:
a) Zmień dla `<button>` nazwę klasy na `mobile-menu__open-btn` i zamiast atrybutu `data-menuMoblie-open` zmień na `mobile-menu--open`
b) Zmień dla `<svg>` nazwę klasy na `mobile-menu__open-icon`
c) Dodaj w `<use>` na początku ścieżki `./` przed `images/icons/sprite.svg#icon-burger`

5. Linijki 24 - 28:
a) Zmień dla `<button>` nazwę klasy na `menu__btn` i dodaj atrybut `modal-window--open` 
b) Zmień dla <span> nazwę klasy na `menu__btn-label`
c) Zmień dla `<svg>` nazwę klasy na `menu__arrow-icon`
d) Dodaj w `<use>` na początku ścieżki `./` przed `images/icons/sprite.svg#icon-arrow`

6. Linijki 29 - 33:
a) Dla `<div class="menu-mobile">` zmień klasę na `mobile-menu`
b) Dla `<div class="menu-mobile__backdrop is-hidden" data-menuMobile>` zmień nazwy klas na `mobile-menu__backdrop` oraz `mobile-menu--is-hidden` oraz zastąp `data-menuMobile` atrybutem `mobile-menu`
c) Dla `<div class="menu-mobile__window">` zmień nazwę klasy na `mobile-menu__window`

7. Linijki 34 - 38:
a) Zmień dla `<button>` nazwę klasy na `mobile-menu__close-btn` i zamiast atrybutu `data-menuMoblie-close` zmień na `mobile-menu--close`
b) Dodaj dla `<svg>` nazwę klasy `mobile-menu__close-icon`
c) Dodaj w `<use>` na początku ścieżki `./` przed `images/icons/sprite.svg#icon-close`

8. Linijki 39 - 43:
a) Zmień dla `<button>` nazwy klasy na `menu__btn` oraz `mobile-menu__btn` i dodaj atrybut `modal-window--open` 
b) Zmień dla <span> nazwę klasy na `menu__btn-label`
c) Zmień dla `<svg>` nazwę klasy na `menu__arrow-icon`
d) Dodaj w `<use>` na początku ścieżki `./` przed `images/icons/sprite.svg#icon-arrow`

9. Linijki 44 - 55:
a) Zmień dla `<ul>` nazwę klasy na `mobile-menu__list`
b) Zmień dla elementów `<li>` nazwy klas na `mobile-menu__item`
c) Zmień dla linków `<a>` nazwy klas na `mobile-menu__link`, natomiast dla linku aktywnego dodatkowo zmień klasę z `active` na `link--active`

2022-03-17 12:11 UTC, patryktomasztomaszek requested changes
Troszkę jest, gdybyś potrzebował pomocy to śmiało pisz

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/images/icons/sprite.svg
> +<path fill="none" stroke="#d41443" stroke-width="6.4" stroke-miterlimit="4" stroke-linecap="round" stroke-linejoin="round" style="stroke: var(--color1, #d41443)" d="M3.2 3.2l12.8 12.8-12.8 12.8"></pa
Usuń z pliku wszystkie instrukcje `fill`
Nie będzie możliwości późniejszej zmiany kolorów

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +    <div class="header-section__menu">
Sugeruję nadać klasę `menu`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +        <div class="menu-logo">
Sugeruję zmianę na  `menu__logo--container`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +            <a href="#" class="menu-logo__link">
Sugeruję zmianę na `menu__logo-link`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                <img src="images/logo.jpg" alt="icecream" class="menu-logo__link__logo">
Sugeruję zmianę na `menu__logo-image`
Scieżka do pliku powinna zaczynać się od `./`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +        </nav>
Sugeruję zmianę klasy na `nav` dla tego i poniższych elementów

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                <li class="menu-nav__list__item"><a class="menu-nav__list__item-link active" href="#">home</a></li>
`active` nie wskazuje we własnej nazwie co jest aktywne, sugeruję zmieną na `link--active`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                <li class="menu-nav__list__item"><a class="menu-nav__list__item-link" href="#contact">contact</a></li>
Sugeruję zmianę klasy elementu `li` na `nav__item`, a dla elementu `a` na `nav__link`.

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +        <button class="menu-mobile-open-bnt" type="button" data-menuMoblie-open>
Sugeruję:
`menu-mobile__open-btn`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +            <svg class="menu-mobile-open-bnt__icon">
Sugeruję:
`menu-mobile__open-icon`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                <use href="images/icons/sprite.svg#icon-burger"></use>
Link powinien zaczynać się od `./`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +            <div class="menu-mobile">
Podobnie, jak dla elementu `button` powyżej

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +<header class="header-section">
Brak elementu o klasie `container`
Może być później problem z adaptacją dla zmiany rozmiaru wyświetlania

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                        <button class="menu-mobile-close-btn" type="button" data-menuMobile-close>
Sugeruję:
`menu-mobile__close-btn`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                                <use href="images/icons/sprite.svg#icon-close"></use>
Link powinien zaczynać się od `./`

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/partials/header.html
> +                        </ul>
Tu podobnie jak powyżej

2022-03-17 12:11 UTC, patryktomasztomaszek commented on src/sass/main.scss
> +@import "./headre";
nazwę pliku zmień na `_header.scss`

2022-03-17 17:02 UTC, dawidmarek95x approved these changes

2022-03-17 17:03 UTC, merged